### ISSUE TITLE
trying to self-review a patch with :me causes errors

### ISSUE THREAD

**Issue by froydnj** [mozilla/git-bz-moz#77] opened 2016-01-27 17:23 UTC
Carrying forward review on a patch (or just self-reviewing a trivial patch) by uncommenting the `:me` option leads to:

```
Multiple bugzilla users matching ":me":

  1. Dave Justice [:JSON_voorhees / :meandave] <djustice@mozilla.com>
  2. Tobias Kristiansson [:mediocrity] <kristiansson.tobias@gmail.com>
  3. Michael K. Edwards (:medwards) <m.k.edwards@gmail.com>
  4. Mekki MacAulay [:mekki] <mekki@mozillacanada.org>
  5. Agamemnon Skepetaris [:memos] <memos.ironheart@gmail.com>
  6. Merike (:merike) <merikes.lists@gmail.com>
  7. Melissa O'Connor [:melissa] <moconnor@mozilla.com>
  n. None

  a. Abort
```

which is unpleasant.  I'm not sure what broke this, but we should fix it.

**Comment by amccreight** [comment] 2016-01-27 19:05
I actually used this just the other day in bug 1240904, without issue. So I'm not sure what the extra factor is that is causing problems for you. I think I've seen it too at some point. This code is pretty hacky, IIRC.

**Comment by amccreight** [comment] 2016-01-27 19:19
Did you uncomment your :me that was inserted based on the r= thing and not the :me+? I can't reproduce the behavior with your initial subject line in bug 1243430.

**Comment by amccreight** [comment] 2016-01-27 19:19
:me isn't supported only :me+ is.

**Comment by amccreight** [comment] 2016-01-27 19:26
The subject line says :me which is not supported so I'm going to close this as invalid. :P Presumably the r=me inserted as the first line based on the commit message was confusing. This seems like an odd corner case so I think we can just leave it alone, but feel free to write a patch or something if you think this could be improved.

**Closed by amccreight** 2016-01-27 19:26 UTC
