### ISSUE TITLE
attach is broken when enabling experimental bugzilla interface

### ISSUE THREAD

**Issue by lissyx** [mozilla/git-bz-moz#43] opened 2015-03-30 09:54 UTC
If user sets "Use experimental user interface" to "On", to benefit from the new modal UI, then attach gets broken:

Traceback (most recent call last):
  File "/home/alex/codaz/Mozilla/moz-git-tools/git-bz", line 2563, in <module>
    do_attach(*args)
  File "/home/alex/codaz/Mozilla/moz-git-tools/git-bz", line 1937, in do_attach
    bug = Bug.load(handle)
  File "/home/alex/codaz/Mozilla/moz-git-tools/git-bz", line 1463, in load
    bug._load(bug_reference.id, attachmentdata)
  File "/home/alex/codaz/Mozilla/moz-git-tools/git-bz", line 1203, in _load
    etree.parse(response)
  File "<string>", line 38, in parse
cElementTree.ParseError: not well-formed (invalid token): line 7, column 91

**Comment by amccreight** [comment] 2015-03-30 22:42
Yeah, that's unfortunately not super surprising.  Ideally, this would use bzapi instead of parsing HTML.

**Comment by globau** [comment] 2015-04-01 15:41
/me casually mentions http://bugzilla.readthedocs.org/en/latest/api

**Comment by amccreight** [comment] 2015-04-01 18:10
Yeah, I think this is really a duplicate of issue #30, as it isn't worthwhile to really further change whatever scary HTML parsing this does.  Probably we can even just reuse code that bzexport does to do stuff.  So I'll just close it in favor of that.

**Closed by amccreight** 2015-04-01 18:10 UTC

**Comment by Rik** [comment] 2015-04-14 13:30
Maybe a temporary workaround would be to use `?format=default` when scraping the HTML?

**Comment by lissyx** [comment] 2015-04-14 13:38
Looks like it's helping ...

**Comment by amccreight** [comment] 2015-04-14 14:00
Another sort of workaround is Seth added a wrapper for hg bzexport to moz-git-tools, so if you have that installed in your hg repo then you can use it to do stuff:
https://github.com/mozilla/moz-git-tools/pull/43
