### ISSUE TITLE
RuntimeError: git rev-list didn't return a number of lines divisible by 3

### ISSUE THREAD

**Issue by past** [mozilla/git-bz-moz#89] opened 2016-11-23 12:02 UTC
I'm using git-cinnabar, but the stack points to git-bz-moz so I'm filing here.

## STR
In a local git-cinnabar clone of mozilla-central (e6b1d0421ae97595aa632d3de79a55ef43fabab8):

```
$ git bz apply 1109868
Bug 1109868 - XUL popups with an anchor element should hide when the anchor loses its visibility and/or frame

Hide or move popups when the anchor changes
Apply? [yn] y

Applying: 
.git/rebase-apply/patch:628: trailing whitespace.
function waitForPanel(panel, event)  
warning: 1 line adds whitespace errors.
Traceback (most recent call last):
  File "/Users/past/src/git-bz-moz/git-bz", line 1788, in <module>
    do_apply(*args)
  File "/Users/past/src/git-bz-moz/git-bz", line 1170, in do_apply
    commits = rev_list_commits("HEAD^!")
  File "/Users/past/src/git-bz-moz/git-bz", line 203, in rev_list_commits
    raise RuntimeError("git rev-list didn't return a number of lines divisible by 3")
RuntimeError: git rev-list didn't return a number of lines divisible by 3

```

**Comment by amccreight** [comment] 2017-03-13 18:33
Hmm. Well, unfortunately this does not reproduce any more because the patch is really out of date.

**Comment by past** [comment] 2017-03-13 18:49
It is weird that the patch doesn't even apply when checking out the same changeset I mention above. I am pretty sure that's the same setup I had back then.

**Comment by amccreight** [comment] 2017-03-13 18:51
I guess I'll close this for now. Sorry I didn't look into this when you first filed it. Please reopen if you see it again. (Getting the output of the rev-list command would likely be useful.)

**Closed by amccreight** 2017-03-13 18:51 UTC
